### ISSUE TITLE
Fortnightly Hackathons

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#11]
Let's kick off hackathons each second weekend.
## Hackathon Format
- Starts at 12pm Saturday Sydney Time, and continues until the end of Sunday for each person
- There will be a hangout on air and google drive document to set the goals and get the community participating
- Specific IRC channel to be announced later
- While there will be a specific focus, you are also free to hack on whatever you want
## Upcoming Hackathons
- [**10-11 of May — Website Refresher**](https://plus.google.com/events/cpojta47o4g75g08vn3bm2olj0k)
  - Hackathon Briefing - http://goo.gl/Q8x7pU
  - Redo the Startup Hostel website as a network
  - Get the [new DocPad](http://new-docpad.org/) Website up and running
  - Get the new Bevry Learning Centre up and running
- **24-25 of May — [CampJS](http://campjs.com/)**
  - @interconnectapp, [WebRTC](http://www.webrtc.org/), Web Components, [Polymer](http://www.polymer-project.org/)
- **7-8 of June — Abstract All The Things**
  - [DocPad Yeoman Generator](https://github.com/RobLoach/generator-docpad)
## Proposals
- @InterConnectApp & [Polymer](http://www.polymer-project.org/) & CommonJS
- [Abstract all the things from DocPad](https://github.com/bevry/docpad/issues?milestone=16&page=1&state=open) & Plugins Hacking
- Give it a gui - @WebWrite HackAttack, and/or hack on other DocPad editors
## Physical Meetups

Post your city in the comments and one of our moderations will add it to [this map](https://github.com/bevry/meta/blob/master/community.geojson) using [this editing interface](http://geojson.io/#id=github:bevry/meta/blob/master/community.geojson&map=0/15/-79) and [this geocoder](http://api.tiles.mapbox.com/v3/examples.map-zr0njcqy/geocode/Berkeley.json)

**Comment by mikeumus** [comment]
_Love this idea._ :heart_eyes:

**Comment by ahdinosaur** [comment]
also love this idea. :+1:

**Comment by balupton** [comment]
This is when everyone goes woop woop woop!

Bevry Hackathon 1: Website Refresh event is now up:
https://plus.google.com/b/100631142988286661025/events/cpojta47o4g75g08vn3bm2olj0k

Big thanks to @mikeumus for putting this together!

**Comment by balupton** [comment]
Putting it on the backburner for now, we need to build a stronger and tighter community first before we start doing hackathons.
