### ISSUE TITLE
Special Hangout Formats

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#12]

**Comment by greduan** [comment]
Just to add an idea for this. Make a 1 hour hangout where we only talk with text chat, or in another hangout which is private but it's being aired. On April Fools day or just any day.

And post it as an "IMPORTANT!" link somewhere with exposure. :)

**Comment by balupton** [comment]
@mikeumus's suggestions from https://github.com/bevry/meta/issues/1#issuecomment-40886117

As per today's Catchup5 Hangout, we have the idea to mix up the topics of our hangouts so that everyday isn't just shop talk. Ideas are as follows:
- Certain days should be issue house cleaning days and there should be braindump days as well were you cover in detail a piece of DocPad.‏ ‎As much as we want to help, your still the one that coded most of it and without dumping, we won't ever be able to follow/relate properly/fully.‏
- Maybe another type of hangout where we interview someone who uses a Bevry product like DocPad or interview someone interesting and relevant like maybe someone from the polymer team so that it becomes on those days something that people will actually want to watch independent of Bevry.‏
- And finally on some days we can have mini-hacks on any project for social good. Like three hours where we contribute somehow effectively, be it hunting/fixing bugs, etc...‏ Like contributing to Loomio, specifically on their open democracy initiatives or live hacking on Bevry GitHub issues/features. For example: http://www.osa-ears.org/ is a good one too looking for technical help.‏ It'd be neat to pair-program or VIM Multiuser for these days: https://github.com/emgram769/vim-multiuser (this was a awesome project out of HackPSU.)

**Comment by mikeumus** [comment]
We should do some brain-dumps this week leading to the hackathon.

**Comment by greduan** [comment]
I was thinking the same. :)

**Comment by balupton** [comment]
Putting this on hold until our community is stronger.
