### ISSUE TITLE
Geolocating our Community

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#13]
Would be really cool to show our members across the globe for the purpose of organizing in-person distributed hackathons every fortnight #11 

I've created https://github.com/bevry/meta/blob/master/community.geojson however I think we could probably automate this by scanning the GitHub API which we already do for the new bevry website, but we could take this further by fulling automating this.

With https://github.com/bevry/meta/blob/master/community.geojson people need to add themselves manually, with the proposal, if you are a _member_ of our any of our GitHub organisations, you'll show up on our map.

At first I figured this sucks because it only allows members to be added, but then again, it is likely only to be the members which are passionate enough to actually organise in-person hackathons in their local areas anyway, and if there is a non-member who wants to do so, then we need them as a member!

Technologies we can use:
- https://github.com/blog/1528-there-s-a-map-for-that
- http://leafletjs.com/
- https://api.github.com/orgs/bevry/public_members
- https://api.github.com/users/balupton
- https://www.mapbox.com/developers/api/geocoding/#forward

**Comment by ahdinosaur** [comment]
i really like the idea of mapping our network. :)

i made a basic interface for viewing the Bevry `community.geojson` file at [dinosaur.is/community](http://dinosaur.is/community). source is [here](https://github.com/ahdinosaur/community). it needs lots of work, but it's a good start using [leafletjs](http://leafletjs.com/). the next steps are to have it use the remote `community.geojson` file (having problems with CORS) and also use [leaflet-markercluster](https://github.com/Leaflet/Leaflet.markercluster).

**Comment by balupton** [comment]
Sweet, if we combine your rendering solution with https://gist.github.com/balupton/9187991c53d801f654e3 then we'll have a complete solution.

Note that gist needs some work, currently improving it.

**Comment by balupton** [comment]
Got the awesomeness going. Say hello to [chainy](https://github.com/bevry/chainy/blob/master/chainy.coffee). Will do release it properly tomorrow.

**Comment by ahdinosaur** [comment]
awesome!

i updated the [map](http://dinosaur.is/community/) and started [geojson-mapify](https://www.npmjs.org/package/geojson-mapify).

it would probably be best for this to be a Web Component, right?

**Comment by balupton** [comment]
just discovered I never posted the result from the chainyjs solution, here it is http://code.runnable.com/U6ichlSIeJ8quen5/create-a-geojson-file-for-your-github-communities-for-node-js-and-chainyjs

**Comment by balupton** [comment]
Closing.

Bevry meta discussions should now occur at https://discuss.bevry.me

For this issue, we should move away from the notion of a community, and move towards the notion of initiatives.
