### ISSUE TITLE
Consider license change

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#16]
I think it's time that we stop closed proprietors from shitting on our face.

Currently the MIT license allows everyone to take, however, only those aligned with free culture give back. The rest just take.

Considering this, I'm putting forward the following:
- If you are using Bevry software to build libre software, you may use it for free
- If you are using Bevry software to build non-libre software, you must pay a monthly license fee
- If you are using Bevry software to build libre and non-libre software, you must pay a monthly license fee

It's unacceptable that those earning money from our software, do not give back. It's unacceptable that those earning money from our software, expect a premium level of product, service and support for free. It's unacceptable that those earning money from our software, would prefer to complain than to send a pull request.

Gittip is great, but the notion of generosity is oil and water to the non-libre and libre world.

All in all, I've learnt the following things:
- When licensed under the AGPL, people just violated our terms and stole our work anyway
- When licensed under the MIT license, the culture of open-source consumerism became permissible, and thus became encouraged through lack of discouragement, and thus became widespread
- Losing freeloaders is not a loss
- Taking money from those who have it is not a loss
- Taking money from those who want to give it is not a loss
- Taking money used for bad, to use it for good, is good (as it gets the money out of the destructive system)
- Not assisting people accomplish bad, is good (a eventually no one will be left to accomplish bad)
- Not taking the money/power from those doing bad/non-libre, so we can use it to do good, is bad (as it lets the money cycle in a bad system, causing further damage with each change of hands)

Todo:
- [ ] Find a "give back" license that accomplishes the terms that are put forward above
- [ ] Write a script to update all our repos with the new license
- [ ] Do up a recurly+stripe payment mechanism and invoicing to handle the licensing fees

/cc @bevry/meta-team

**Comment by greduan** [comment]
Although I like this idea it sorta feels cheap. That's just because of my own values though.

We also have to talk about how much people would have to give us with the monthly subscription...

**Comment by ahdinosaur** [comment]
i propose a different license (maybe possible to fork the [Peer Production License](http://p2pfoundation.net/Peer_Production_License)):
- If you are using Bevry software to build libre software, you may use it for free
- If you are a Bevry contributor, you may use it for free
- If you are using Bevry software to build any non-libre software and are not a Bevry contributor, you must share a percentage of your revenue and publicly post your sharing rate

this is related to https://github.com/ahdinosaur/contributor-agreement/issues/4.

**Comment by greduan** [comment]
That looks like a good proposition as well.

**Comment by pflannery** [comment]
@balupton I understand how you feel about this and I agree that some people are just p-takers.

For my own projects current and future I intend to stick with MIT license as I'm happy for all people to use my software regardless. I share my work for free for anyone to use and don't expect anything in return. Every person\org that uses my software is a reward\satisfaction to me if they do, and if not I'm using it myself anyway.

Yeah there are potentially people that will use it to make money for themselves buts that's a good thing not a bad thing. The way I see it is: if I've written something that is a solid piece of work that is a part of someone else's project's success then this just spreads my work to others and creates a network of people that will inevitably bring something in return to my project.

**Comment by greduan** [comment]
I think the idea is to charge because it's proprietary software instead of free software.

I say just leave them be, since I really like the ISC license. I would vote for an ISC license if a vote is opened for this.

**Comment by ahdinosaur** [comment]
the idea is to charge those who don't already contribute back to the commons, as otherwise their success can be _at the expense of_ and _detrimental to_ the commons. as workers for [commons-based peer production](http://p2pfoundation.net/Category:Peerproduction), we want to prevent others who don't share our values from profiting off of our labor. a good example of corporate profit on the backs of open source is [Makerbot](http://www.makerbot.com/), which started as a fork of the [RepRap project](http://reprap.org/): [in-depth article](http://outsidethetext.com/theworkofplastic/blog/2014/06/11/makerbot-raiding-the-commons/), [Open Value Network pitch](http://youtu.be/9h7Z9LPQwmw).

**Comment by greduan** [comment]
I see.

We can always go the extreme route and go with GPL...

In any case, we can talk about this in a voice chat where it's live. :)

**Comment by balupton** [comment]
@pflannery the issue was pretty much nailed by @ahdinosaur but to paraphrase a bit, sure it's all and well having people use our stuff, the problem though is usually non-libre people give back whereas non-libre people don't, so each support request they do, each feature request they do, each complaint they do, is an issue — as a product becomes more popular, the costs of maintenance increase exponentially; and it's not something that can be solved by pumping more contributors into the system, as there is still operating and organisation costs, and there is always still rent and bills to pay (unless the moneyless thing catches on way further — still years to go for that). So as @ahdinosaur said, it's about stil letting people use our software as liberally as possible, but leveraging that the non-libre people are use to paying for software and licenses, the work already done. If that can be leveraged, rather than missed out on, then it becomes easier to maintain the projects. The other aspect of this is an ethical aspect, where if you are a small-time company, and cannot afford the license fee, then perhaps you should be doing libre software or charging more, as unlike corporate gigantics, one can be more lenient with IP in small companies.

@ahdinosaur's proposal seems further down the line of this, as it incentivises contributions from everyone, so I need to evaluate it further.

@Greduan yeah, GPL can be a portion of it, but it just excludes non-libre people, rather than benefiting from them.

**Comment by pflannery** [comment]
@balupton what do you define as contribution?

**Comment by balupton** [comment]
@pflannery pull request saving us time, or financial donation buying us time

**Comment by pflannery** [comment]
@balupton fair enough. how about promotion and the sort?

I definitely don't like the idea that someone could fork your project, close it's source and sell it off without giving anything back. I equally don't like the idea of contributing to a project that then closes it's source to make profit without giving back to the contributors.

I've been looking at a [Non profit license](http://opensource.org/licenses/NPOSL-3.0) maybe this with a clause that ensures contribution back to the project otherwise a license fee is required?

**Comment by ahdinosaur** [comment]
i define 'contributor' slightly different than 'one who provides contributions' according to @balupton's definition of 'contribution'. i see contributors as the "worker-owners" of the project, so to become a contributor it's not enough to get a pull request merged (in services like [tip4commit](https://tip4commit.com/) we see people trying to push many minor pull requests so they can get tips), you need to become a member of the [project team](http://producingoss.com/en/committers.html), usually through continued quality contributions and a decision in favor from existing contributors. currently (https://github.com/ahdinosaur/contributor-agreement/issues/4), i think this sort of arrangement needs both a license and a contributor agreement to work properly.

**Comment by bhaugen** [comment]
What if work contributions went only for solving team-defined issues, and each issue gets a credit rating up front? This was the way BetterMeans did it, and it made sense to me. (Although BM died ugly, I don't think that is why they self-destructed.)

**Comment by balupton** [comment]
Closing for now. I suspect the issue is more due to the difficulty and lack of transparency around our support and sponsorship packages. We should try to improve the workflow of people giving us money first, before we do such a radical change as changing license.
