### ISSUE TITLE
Move only to free and better yet, libre software

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#17]
It should be essential that our stack runs on free software, and better yet, libre software.

Currently, we use the following paid software:
- Zapier for synchronisation tasks
  - Could be replaced by a chainy-based bevry/helper-service
- Sketch for OSX
  - I've emailed them about providing free licenses for open-sourcers, but haven't got any response

Currently, we use the following free software:
- Cloudflare for dns, performance, and protection
  - Replacements ???
- Heroku for hosting
  - Replacements ???
- Github for code
  - Replace with GitLab #15 
- Google Hangouts for meetings
  - InterConnect?
- Gmail
- Skype for chat
  - InterConnect?
- OSX
  - Ubuntu or Ubuntu Gnome?

/cc @bevry/bevry-core-team

**Comment by mikeumus** [comment]
I think @ahdinosaur may have some good insights here.

**Comment by ahdinosaur** [comment]
thanks for the mention @mikeumus, watching the repo now.

where do we want to focus first?

i can help with migrating personal machines to linux, but that's more of a personal experience based on how you want to interact with your daily computer. i recommend we try to leverage Docker to host our sites and manage our DNS, if given more details i can help more, if given access to a cloud machine i can really help. as for communication, we really should dogfood InterConnect more, @balupton how much funding do you need to develop it to be usable for teams like Bevry?

**Comment by mikeumus** [comment]
I'm willing to go in financially on Interconnect as well. And as you touched on hosting DinoMike, I think running our own recycled machines on solar would be the pinnacle of principle alignment with what we're trying to do and we could probably do this with a small budget for our staging/development servers at least. #2cents  

However there are trade offs for everything. How practical/efficient using recycled machines is, I don't know yet.

**Comment by ahdinosaur** [comment]
@mikeumus that's a great idea. :thumbsup:  first step, do we have a location for running our own recycled machines on solar?

**Comment by mikeumus** [comment]
I have a couple machines and I have to learn more about SolarCity, but yeah in my garage as an option.

**Comment by ahdinosaur** [comment]
sweet, that works with me. if we want to do something now while we don't have actual solar panels running the machines, we can do something similar to [Electric Embers](http://electricembers.coop/about-us/why-choose-us/) and purchase carbon offsets from [Native Energy](http://www.nativeenergy.com/how-carbon-offsets-work.html). also, if you do want to install solar panels, SolarCity is not your only option. maybe this "hardware" discussion should be in a separate issue, as the original post was about software.

**Comment by mikeumus** [comment]
The software can be libre but it's the electricity really that we care about here (for hosting/servers) as linux web hosting servers are already free (Ben and I are chatting about this, in a way). I will call SolarCity tomorrow and fallback to others as you pointed out. What's a good version of linux I should attempt on these power machines from early 2006 ?

**Comment by greduan** [comment]
A replacement for OS X is obviously Linux, I use Arch Linux, I would encourage you guys to try that out but I don't think you guys would be willing to spend a day learning how to install a Linux distro. lol

In all seriousness though, old computers would benefit the most from Gentoo probably, but that is not something for mere mortals to automatically install. lol

I remember there was a distro specifically for old computers... uh... Puppy Linux? http://www.puppylinux.com/ I dunno

Really any distro that doesn't install a bunch of crap for you is light enough, IMO.

Instead of Heroku maybe DigitalOcean? For all of the chats InterConnect seems to be the popular answer, so should we just finish that one first?

**Comment by ahdinosaur** [comment]
> In all seriousness though, old computers would benefit the most from Gentoo probably, but that is not something for mere mortals to automatically install. lol

since Gentoo requires compiling all packages, it is a bad idea for old computers as compiling takes forever. Gentoo only works if you have a farm of machines that can compile once for all of them.

> Really any distro that doesn't install a bunch of crap for you is light enough, IMO.

i'd recommend we use either Debian or Arch Linux, that way we can build our infrastructure regardless of if it's on old or new machines. i personally use Debian for all my machines now, but that's a personal preference.

**Comment by greduan** [comment]
> Gentoo only works if you have a farm of machines that can compile once for all of them.

Fair point, but, since it's compiled specifically for that hardware it's quicker. :)

The compiling sucks, but the results are cool.

**Comment by balupton** [comment]
I hear this argument for specific builds for old machines a lot. Having tried many, including the lubuntu etc, their usability is a real compromise, and I'm not sure there is much to win over the mainstream Ubuntu build.

**Comment by greduan** [comment]
Well I mean, this is not really something for me to discuss since I'm already full-time on Linux. But I wouldn't suggest Ubuntu to anyone. Whether they are beginners or not.

So you guys go with whatever you guys like, but I'll only recommend and "support" Arch. :)

**Comment by ahdinosaur** [comment]
my understand is that these old machines would be headless, so they don't need a graphical user interface. for our personal machines that do need a graphical user interface, presumably they have enough power for our favorite desktop environments, based on our own opinions of usability. we can run headless servers or our favorite desktop environment using Debian or Arch Linux, they are flexible for all situations.

**Comment by balupton** [comment]
For what it's worth, the server and backend architecture is something I'm happy to 100% delegate to someone else who knows better than me! Leaving myself completely void of opinion if delegated :)

**Comment by greduan** [comment]
Oh we were talking about servers? In that case I wouldn't use Arch Linux. I would use something Debian, so Ubuntu is fine.

I was talking from the perspective of the environment that we'll install in our laptops.

**Comment by balupton** [comment]
This is to impractical.
