### ISSUE TITLE
Fund Interconnect

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#18]
@ahdinosaur as you're part of enspiral which had a successful crowd-funding campaign for Loomio, I'm happy to make you the go to person for this.

**Comment by ahdinosaur** [comment]
@balupton, how much funding do you need to produce an alpha version of Interconnect that can be used by Bevry and Enspiral?

**Comment by balupton** [comment]
@ahdinosaur's feedback is we need a roadmap for what price will accomplish what features

**Comment by balupton** [comment]
Meeting scheduled between @balupton and @ahdinosaur open to others here:
https://plus.google.com/b/100631142988286661025/events/c65ccvk8pgvp9i81404h0h6em88

**Comment by greduan** [comment]
Woo voice chat. :D 

Since it's at 9PM I won't be able to stay for _too_ long but I'll do my best to stay the longest I can. :)

**Comment by balupton** [comment]
Awesome, great to have you join us @Greduan :-)

**Comment by greduan** [comment]
It is time...

**Comment by ahdinosaur** [comment]
i'm ready to go. where is @balupton? also is there a link to the hangout?

**Comment by balupton** [comment]
I slept in.... :O To think I made an event and everything, but forgot to set an alarm. Sorry everyone, will reschedule for later today.

**Comment by balupton** [comment]
this https://twitter.com/dotjs/status/510358228358922240

**Comment by balupton** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYcmSRiCIlUatu_WPPKazjgI3IuMo3oibN4NwjYjg-B-e7xmmg

**Comment by balupton** [comment]
https://hackpad.com/interconnect-A9FAE0A0HYT

**Comment by balupton** [comment]
Putting this on the backburner, as our focus is with DocPad for the next 6 months.
