### ISSUE TITLE
Team rejig

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#19]
Hey @bevry and @docpad I've rejigged the teams a bit.
- DocPad is now part of the DocPad GitHub Organisation https://github.com/docpad/docpad/issues/833
- Documentation teams are now Meta teams, having access to the meta repo
- Helpers team is now Extras Team
- @ahdinosaur has been added to the DocPad and Bevry meta teams

**Comment by greduan** [comment]
OK cool. Thanks for letting us know. :)

**Comment by balupton** [comment]
I've added the other DocPad meta members to the Bevry Meta team too. Welcome @hal-gh @zearin

**Comment by balupton** [comment]
@hal-gh seems you denied the invitation?
