### ISSUE TITLE
DocPad Marketing message

### ISSUE THREAD

**Issue by mikeumus** [bevry-archive/meta#2]
I'm focusing on the new DocPad homepage and it's new marketing messages. I need to know more about the awesomeness that is the taskgroup, bal-util, joe so that I can speak succinctly on them. I'll already be speaking on the approach that DocPad is taking by having everything be small pieces and products of their own and the ability to swap out so much of DocPad. How it can be a SSG and also a robust platform for dynamic prototyping as well. 

All prior discussions/issues on the topic I could find:
- bevry/docpad/issues/820 - discussing slogan

**Comment by balupton** [comment]
+1, although I'm unsure if this is still the right place for this issue. Happy to add this to the queue for tomorrow's catchup

**Comment by mikeumus** [comment]
There have been other issues discussing this topic before. We should reference those old issues in the meta issue and close all the old ones to consolidate.

**Comment by balupton** [comment]
The only issue I can recall dedicated to DocPad's marketing is this one: https://github.com/docpad/website/issues/49

With other issues covering marketing as digressions, or in the case of https://github.com/bevry/docpad/issues/820 a user "bug report"

So suggestion here is to close this meta issue in favour of the website issue.

**Comment by mikeumus** [comment]
:+1:
