### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by greduan** [bevry-archive/meta#20]
@bevry/meta-team 

We need a blog. We've discussed this before but I don't think a consensus was reached about where to host the blog and with what it would be done.

I was reminded of this because @balupton said on this issue https://github.com/bevry/meta/issues/15 in the todo section:

> - Do up a blog post about why the move

And I realized a blog hasn't been made yet.

So we gotta make one.

My vote still remains the same, use a static website generator and host it ourselves. I believe Ben prefers to use Tumblr or something of the sort.

If we do host it ourselves, I would suggest using Jekyll because that's the best I've found for simple blogs so far. Of course once DocPad has been re-written we would switch to DocPad.

**Comment by balupton** [comment]
There's a blog: http://bevryme.tumblr.com/

We accomplished it on our hackday.

Post-this, we decided to scratch it, and just use medium instead. Of which we have one there too :-) https://medium.com/bevry-me

We should evaluate svbtle as well, as they have a good branding system.

**Comment by greduan** [comment]
Ah OK.

Cool. I guess we're going to use the Medium one? I still think self-hosted is best though. ;)

**Comment by balupton** [comment]
Perhaps an official communications forum on Discourse will solve this:
https://github.com/bevry/meta/issues/10

**Comment by greduan** [comment]
Again, while I do believe Discourse is great for communication, I don't feel like it's the best place for announcements and stuff. Same for Medium.

I still believe docpad.com should be or have a blog. Or do it like Arch Linux or other such distros which have the news right in the front page.

The website can be very simple but effective http://www.voidlinux.eu/

**Comment by mikeumus** [comment]
Yeah I think we need an official blog as well. You can mod Discourse so
that tagged threads show up on a blog page on the site.

**Comment by balupton** [comment]
Up https://blog.bevry.me and https://blog.docpad.org
