### ISSUE TITLE
Telegram Group

### ISSUE THREAD

**Issue by mikeumus** [bevry-archive/meta#22]
We have setup two internal focused Telegram Groups for communications. One for water cooler conversation, and one for team communication. Telegram is a cross-platform, fast, secure, instant messenger, and for the most part, open-source.

**Comment by Greduan** [comment]
Telegram does look quite nice. I wonder how it would compare to Slack, maybe I can convince some people to switch. :smiling_imp:

**Comment by Greduan** [comment]
Although...

![2015-01-15-162546_1280x800_scrot](https://cloud.githubusercontent.com/assets/2314074/5768110/67b992a0-9cd3-11e4-884b-7bb52bc79c3d.png)

I am not comfortable with providing that info, I wonder if that can be avoided...

Just to make sure, do I need a mobile device for this? Hope not...

**Comment by mikeumus** [comment]
They do it just to send you an SMS to verify that you are a human. And they
have a web interface to chat from as well that is pretty nice.

Mike

**Comment by Greduan** [comment]
I see. And that's just once or is it every time?

**Comment by mikeumus** [comment]
Just once for account setup.

**Comment by Greduan** [comment]
Ah OK. Cool. I gotta ask somebody to help me out cause I don't have a cellphone. :P

**Comment by Greduan** [comment]
OK, I've got an account. My username is `greduan`. What next?

**Comment by mikeumus** [comment]
:mega: :fax: :speaker:

**Comment by mikeumus** [comment]
@ahdinosaur @RobLoach, so much fun in the telegram Bevry room. We miss you guys in here. ... :cry: 


:dancer: :tada: :beers:

**Comment by balupton** [comment]
I got an email from @RobLoach saying he'll join us in Telegram, but no dice yet! Hopefully soon!

For those who want in: http://telegram.me/balupton

**Comment by ahdinosaur** [comment]
... eep, i got chat platform fatigue, but i'll try to join at some point.

**Comment by balupton** [comment]
Updated the original post copy for the latest status. @ahdinosaur would be good to get you in there.

**Comment by balupton** [comment]
@ahdinosaur would be great to have on Telegram while we setup the discourse forum

**Comment by balupton** [comment]
Migrated to: https://discuss.bevry.me/t/telegram-chat-group/37

**Comment by RobLoach** [comment]
https://telegram.org/faq#q-why-not-open-source-everything

I'll be on IRC.
