### ISSUE TITLE
Knowledge Base?

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#26]
Would transitioning our knowledge base like issues to either a wiki, or a proper knowledge base make sense?

**Comment by mikeumus** [comment]
Like GitHub issues that answer questions or issues that are bugs, or both?

**Comment by balupton** [comment]
I was thinking either a discourse forum, github wiki, or confluence, or just migrating those topics to bevry/learn. The issue is the sacrifice of commenting, which is valuable. It's a trivial/low priority issue, but would be good to get some feedback.

**Comment by mikeumus** [comment]
Pardon my question was to what we'd be transferring from GitHub exactly. 
DinoMike already has a droplet live for us to setup Discourse on, just gotta SSH in and do that. I'll add that to my Lifeboard and do it tomorrow.

**Comment by balupton** [comment]
Pretty much these issues: https://github.com/bevry/meta/labels/team%20%2F%20community

**Comment by mikeumus** [comment]
Definitely Discourse gets my vote for this then. We'll be setting it up anyways, the less tools the easier, and having a Discourse forum is a good look on the community allowing for non-code/bug related issues to be better discussed outside of GitHub.com

**Comment by greduan** [comment]
I do think it makes sense. But I feel like a wiki would work better than Discourse, which is a platform to communicate.

I do think Discourse should be our support/help platform though.

**Comment by mikeumus** [comment]
The things Ben linked to are community discussions though... :stuck_out_tongue: 
The 1password thread could be in the private admins section of the Bevry Discourse.

**Comment by greduan** [comment]
Well if we're talking about discussions, then yeah. But If it's for a knowledge base, wiki it is. :)

**Comment by balupton** [comment]
Discourse fulfills this.
