### ISSUE TITLE
Enabling 2FA on all bevry organisation members

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#28]
On one of the organisations I am part of (not bevry related) had a member account compromised by what seems like a malicious script. I would like to take precautions to protect the bevry ecosystem (which has millions of downloads a month).

As such, I wish to enable the [GitHub feature that requires all organisation members to have 2FA enabled](https://help.github.com/articles/requiring-two-factor-authentication-in-your-organization/). To enable this feature, all organisation members must [use 2FA auth on their GitHub accounts](https://github.com/settings/security), or be removed from the organisation.

Here are the members without 2FA enabled, of which I am [requesting to enable it](https://github.com/settings/security), or note that you won't, so I can remove you.

Setting the deadline fo this to be 7 days from now. So 29th June.

[Bevry](https://github.com/orgs/bevry/people?utf8=✓&query=+two-factor%3Adisabled) [members](https://github.com/orgs/bevry/outside-collaborators?utf8=✓&query=+two-factor%3Adisabled)

[DocPad](https://github.com/orgs/docpad/people?utf8=✓&query=+two-factor%3Adisabled) [members](https://github.com/orgs/docpad/outside-collaborators?utf8=✓&query=+two-factor%3Adisabled)

[BrowserState](https://github.com/orgs/browserstate/people?utf8=✓&query=+two-factor%3Adisabled) [members](https://github.com/orgs/browserstate/outside-collaborators?utf8=✓&query=+two-factor%3Adisabled)

---

You can enable 2FA on GitHub via: https://github.com/settings/security

The common options for setting up 2FA auth that I've encountered are:

- [1Password](https://1password.com) - [2FA Guide](https://support.1password.com/one-time-passwords/) - [download](https://1password.com/downloads/) - I use this option, it is paid though
- [Duo Mobile for iOS](https://itunes.apple.com/us/app/duo-mobile/id422663827?mt=8) - A 2FA alternative recommended by the 1Password team
- [Dashlane](https://dashlane.com) - [2FA Guide](https://support.dashlane.com/hc/en-us/articles/115003383365)
- [Authy](https://authy.com/download/) - [iOS](https://itunes.apple.com/us/app/authy/id494168017?mt=8) / [Android](https://play.google.com/store/apps/details?id=com.authy.authy)
- [Google Authenticator](https://support.google.com/accounts/answer/1066447?hl=en) - [iOS](https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8) / [Android](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en)
- [FreeOTP](https://freeotp.github.io) - an open-source option

**Comment by jaspervdj** [comment]
I am only involved in @bevry because I was the original maintainer of the static site generators list.  I'd like to step down since I'm not actively involved anymore and I don't need access to any of the repositories.  :-)

**Comment by dertuxmalwieder** [comment]
As if that would make that much of a difference...

Enabled 2FA anyway - it might be handy after all.

**Comment by balupton** [comment]
> As if that would make that much of a difference...

From a scripts perspective, it no longer allows username/password combinations - only personal access tokens, which are less likely to be reused across services and logged by malware, and which help identify where the compromise occurred.

> Enabled 2FA anyway - it might be handy after all.

cheers

---

> I am only involved in @bevry because I was the original maintainer of the static site generators list. I'd like to step down since I'm not actively involved anymore and I don't need access to any of the repositories. :-)

no worries :-)

**Comment by balupton** [comment]
Thanks everyone who enabled 2FA. Hope to see the others again at some point.

Removed everyone's usernames from the original post now that the deadline has passed.
