### ISSUE TITLE
Bevry needs your funding!

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#3]
_Update: as funds are nearing their end, @balupton is on the lookout for consulting work_

Bevry has currently been sponsor-less since late March. Myplanet, our previous sponsor, has had to focus their funds on other important priorities, which is totally okay. They're still awesome.

That said, I have about at most 2 weeks left before my funds run dry. I have been exploring employment opportunities.

However, I'm wondering, considering the awesome power of the community we have, I'm wondering if the community can come to the rescue here! Previously DocPad and Bevry were funded by consulting, then by corporate sponsors like Myplanet and Meemo, but perhaps we can now be sustainably funded by groups of individuals and companies instead of one at a time.

That said, here's the plan: Lets start a discussion to figure out how yourself, or your company, or your network, can financially support the DocPad Project and the Bevry Community. We have lots of awesome stuff lined up in the future, such as: breaking DocPad up into smaller pieces, writing thorough tests, building a bigger and better community, better documentation, and new projects like Interconnect that aims to bring people closer together through video and will allow everyone to build Skype-like-applications in a few minutes.

So let's get this discussion going and figure this out together! Specifically:
- Let's raise our Gittip donations even higher:
  - https://www.gittip.com/Bevry/
  - https://www.gittip.com/DocPad/
  - https://www.gittip.com/balupton/
  - Other donation options already available via our upcoming website: http://refresh.bevry.me
- Let's open up the discussion below from companies who may be able to sponsor further development or desire prioritised development services
- Let's discuss the option for a one-time crowd funding campaign (though this will take more than 2 weeks I have before my funds run out to put together)

Our target is $6000USD/month to survive, and $7000USD/month to live comfortably, and $8000USD/month to live well. No money will be wasted, it'll all go back directly into making Bevry and Bevry's initiatives even more awesome. Our gittip incomes are the only ones we are currently receiving.

Also, if there is anything I can do, to add more value, do let me know.

**Comment by Naatan** [comment]
I've added my 1000 cents worth, though I think it will be difficult to meet targets unless you find some big investors.

It would be nice to know how much of your efforts will be spend on segmenting DocPad into smaller community-managed libraries. At least I believe that's what the main idea was (can't seem to find the original discussion on this).

**Comment by Naatan** [comment]
Looking at gittip - I have to wonder whether this platform might not be a bit too young for you to depend on which such a significant sum of money. The entire platform is only processing about 10k per week. I know kickstarter is not ideal because it's just a one-time investment type of deal but it might be enough to "kickstart" (that was totally not intentional) funding for DocPad. For that to work you would likely need to bring something "new" to the table that makes DocPad stand out from the competition and itself in its current state. Eg. smart file reference tracking for partial regenerations of the static site (probably not using that description :p).

**Comment by mikeumus** [comment]
@Naatan, I'm working on raising early-stage/seed money for @docport and trying to convince @balupton that this is a sustainable and ever-missing piece of DocPad's ecosystem. My plan to simply to raise the money and return with it and save the day. I'll let you know how that goes.

**Comment by Naatan** [comment]
Interesting, will keep an eye on @docport. I assume this is intended as a service around docpad, not some type of fork?

**Comment by mikeumus** [comment]
correct, it's a DocPad PaaS building in parallel to @webwrite. It's basically WebWrite.

**Comment by dimitarkolev** [comment]
I very much like the idea behind http://www.blender.org/foundation/development-fund/ is monthly subscription with no obligations from the developers of the project. I mean that donations does not give you any power to change their plans, but just let them do their job. Is there a subscription option via PayPal, i don't like using gittip for direct cc payments.

**Comment by balupton** [comment]
I've added our bitcoin address to each of our gittip pages

**Comment by mikeumus** [comment]
:+1: :moneybag:

**Comment by balupton** [comment]
http://refresh.bevry.me/ now has a live amount of how much we are receiving

**Comment by dimitarkolev** [comment]
Do you plan adding pay pal subscription as a donation option?

**Comment by balupton** [comment]
@dimitarkolev turns out there should be a check box when you click "Donate via Paypal" to make it recurrant on your own terms: https://www.dropbox.com/s/vqrqbvit7uwo5o7/Screenshot%202014-04-22%2019.24.40.png

**Comment by dimitarkolev** [comment]
10x (dont know why i didn saw it) i hope you will manage to reach your goals.

**Comment by balupton** [comment]
Just added a stripe credit card payment form to http://refresh.bevry.me/#donate

**Comment by balupton** [comment]
Also, if you're on Gittip, feel free to join our Gittip Communities for the services you use:
- https://www.gittip.com/for/bevry/
- https://www.gittip.com/for/startup-hostel/
- https://www.gittip.com/for/history-js/
- https://www.gittip.com/for/docpad/

**Comment by Naatan** [comment]
Might it make sense to offer reward tiers to high funders? Not for myself (I assist as an individual and will therefore not be a high funder), but for enterprises that might make use of your services or value the idea behind them.

For example you could have "Gold Funders" which would be featured on certain areas of your website/repositories. Whilst "Silver Funders" would only be featured in a readme, etc.

You could still credit smaller funders as well of course, but the high funders would have a way of standing out.

This could entice larger enterprises that value this type of exposure to chip in.

**Comment by balupton** [comment]
DocPad v6.64.3 now includes a donation plea as a notice in the welcome messages

**Comment by balupton** [comment]
@Naatan definitely an option I'm exploring, do you know any SAAS services that makes this really easy?

**Comment by Naatan** [comment]
Not that I'm aware of, but it wouldn't be too hard to track high funders.. unless you get a LOT of them - in which case that would be a nice problem to have right .. ? ;)

**Comment by balupton** [comment]
So I got some work with Prismatik/Thinkmill/Keystone 2 weeks ago, and hopefully that will remain active. Will close this for now as the urgency of the situation has subsided. Will re-open again if the donations are not enough and I am in need of work. Please keep the donations up, as that is still the only way of funding bevry's FOSS initiatives.

**Comment by mikeumus** [comment]
Congratz on the new gig @thinkmill Ben! :smiley:

**Comment by balupton** [comment]
Work is edgy right now, as Prismatik ran out of work for me. So currently doing small jobs here and there.

I'm re-opening this issue, not just because I need money, but because I have two new plans that seem viable:
1. Set up a bevry school — bevry/school — will start off with 1 day trainings once a month
2. Sponsorship of 15 companies that depend on our stuff each donating $100/week on Gittip — seems reasonable and most importantly possible

**Comment by Naatan** [comment]
Can you expand on sponsorships? Would love to pitch for you but need more than just the word "sponsorship" ;)

**Comment by balupton** [comment]
Yep! Working on doing up a proper page, pitch, and other supporting documentation for it.

**Comment by balupton** [comment]
@Naatan here's the idea of the sponsorship in more details: https://github.com/gittip/www.gittip.com/issues/2621

Is this a good idea? Keen to get your feedback on that issue. As I'm aiming to pull an all-nighter tonight to see if it can.

**Comment by balupton** [comment]
@bevry/bevry-core-team what are people's thoughts on doing a crowd-funding campaign for Interconnect? I keep coming back to it, and the more I realise about crowd-funding, the more I realise it could be possible, even without any proper marketing for it.

**Comment by greduan** [comment]
I do think it could work really well. It really has to be brought to the attention of big devs and everything will work out fine. :)

Good marketing helps a lot though. ;)

**Comment by ahdinosaur** [comment]
+1 to crowd-funding campaign for Interconnect. there's little to lose, a lot to gain.

**Comment by balupton** [comment]
Cool, moving interconnect funding campaign to https://github.com/bevry/meta/issues/18

**Comment by balupton** [comment]
Closing due to age.
