### ISSUE TITLE
Action System (Project Management Tool)

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#4]
Let's use this issue to discuss feedback related to our action system.

In the morning I'll add our decisions about trello, huboard, github issues, basecamp, google docs, and finally workflowly here.

A todo for us out of this is:
- add details about our action system and daily hangouts to the Bevry docs
- and where should that aforementioned task go, as an issue here, or on the Bevry docs repo, or in workflowly, or both? We need to outline the process of what is what. I like github issues for discussions, workflowly for actions personally.

**Comment by mikeumus** [comment]
Personally I like the thought of Huboard with Basecamp for core members to have a "private-lounge" for organization. 

We also talked about trying out any of the above tools/workflows for a week and seeing how it goes. That is until we find something that works nicely and then we should stick with that so we don't become a group that tests collaboration tools.

**Comment by balupton** [comment]
https://workflowy.com/shared/eef6cfec-7f0c-b185-49d1-20b047452d42/

**Comment by pflannery** [comment]
Have you guys considered using Youtrack? http://www.jetbrains.com/youtrack/
I've seen it used for other projects in the open source domain and works well for them

**Comment by mikeumus** [comment]
Looks pretty cool. Free for 10 users. Have you used it before @pflannery? Do you know if the projects can be made public urls for everyone to view?

**Comment by pflannery** [comment]
Yes all projects must be public to qualify for the free 10 user license. 
I use it to report issues when Im working with Umbraco 7 here - http://issues.umbraco.org/issues

**Comment by mikeumus** [comment]
How's your experience with it thus far @pflannery and how long have you been using it?

**Comment by balupton** [comment]
Completed: https://github.com/bevry/meta/issues/23
