### ISSUE TITLE
Setup a Bevry YouTube channel?

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#5]
Todo: fill this out with the pros and cons.

**Comment by mikeumus** [comment]
I vote Yes.

**Comment by balupton** [comment]
Another aspect to this is a google calendar that people can subscribe to. Discussed in Catchup 3:
https://docs.google.com/document/d/1IbXILjh_FW6jRtUFNbv5V96whF8mgXA8t3qchZtojOg/edit?usp=sharing

**Comment by mikeumus** [comment]
Yeah, we can create that calendar from the bevry@gmail or whatever the common Bevry Google Apps account is.

**Comment by mikeumus** [comment]
Ben has this account ready which we'll be creating our official @Bevry Catchups YouTube channel and Google Calendar events starting tomorrow.
