### ISSUE TITLE
Use tumblr for our blog?

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#6]
Will fill out pros and cons tomorrow.

**Comment by mikeumus** [comment]
I vote yes for now while everything is shifting so much. Much better to he quick/dirty and have a blog than not right now.

**Comment by mikeumus** [comment]
See loomio poll:
https://www.loomio.org/d/qnDXSrG5?proposal=10367

**Comment by mikeumus** [comment]
@loomio was a success in helping us choose Tumblr as an immediate and official blogging platform for DocPad and Bevry. Thank you for everyone that participated in the loomio pooling.
